### 학생테이블에 입력/수정/삭제/검색하는 파이썬 프로그램 개발

# DB 연결

In [1]:
import sqlite3

con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
cur = con.cursor()

# 학생 정보 입력

In [2]:
# Insert 1
# sql = "insert into TSTUDENT(HAKBUN, NAME, SEX, DEPT, HP, POST, ADDR) values ('120211206','최장호','남','인공지능','010-2848-6170','55143','완주군');"
# cur.execute(sql)
# con.commit()
# con.close()

In [3]:
#Insert 2

import sqlite3

def insert():
    HAKBUN = input("학번 : ")
    NAME = input("이름 : ")
    SEX = input("성별 : ")
    DEPT = input("전공 : ")
    HP = input("전화번호 : ")
    POST = input("우편번호 : ")
    ADDR = input("주소 : ")

    sql = "insert into TSTUDENT(HAKBUN, NAME, SEX, DEPT, HP, POST, ADDR) values ('{}','{}','{}','{}','{}','{}','{}');".format(HAKBUN, NAME, SEX, DEPT, HP, POST, ADDR)

    con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")

    cur = con.cursor()
    cur.execute(sql)
    con.commit()
    con.close()

# 학생 정보 수정

In [4]:
#Update
import sqlite3
def updata():
    con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
    cur = con.cursor()

    # 수정할 학생의 학번 입력 받기
    HAKBUN = input("수정할 학생 학번 입력 : ")

    # 수정할 정보 입력 받기
    NAME = input("이름 : ")
    SEX = input("성별 : ")
    DEPT = input("전공 : ")
    HP = input("전화번호 : ")
    POST = input("우편번호 : ")
    ADDR = input("주소 : ")

    # 학생 테이블의 해당 학생 정보 수정
    sql = "UPDATE TSTUDENT SET NAME = '{}', SEX = '{}', DEPT = '{}', HP = '{}', POST = '{}', ADDR = '{}' WHERE HAKBUN = '{}';".format(NAME, SEX, DEPT, HP, POST, ADDR, HAKBUN)
    cur.execute(sql)

    con.commit()
    con.close()

# 학생 정보 삭제

In [5]:
#DELETE

import sqlite3
def delete():
    con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
    cur = con.cursor()

    # 삭제할 학생의 학번 입력 받기
    HAKBUN = input("삭제할 학생 학번 입력: ")

    # 입력 받은 학번을 가진 학생 정보 삭제하기
    sql = "DELETE FROM TSTUDENT WHERE HAKBUN = '{}';".format(HAKBUN)
    cur.execute(sql)

    
    con.commit()

    
    con.close()

# 학생 정보 검색

In [6]:
#SEARCH

import sqlite3
def search():
    con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
    cur = con.cursor()

   
    HAKBUN = input("검색할 학생 학번 입력: ")

    
    sql = "SELECT * FROM TSTUDENT WHERE HAKBUN = '{}';".format(HAKBUN)
    cur.execute(sql)

    # 검색 결과 출력하기
    result = cur.fetchone()
    if result:
        print("학번: ", result[0])
        print("이름: ", result[1])
        print("성별: ", result[2])
        print("전공: ", result[3])
        print("전화번호: ", result[4])
        print("우편번호: ", result[5])
        print("주소: ", result[6])
    else:
        print("해당하는 학생의 정보가 없습니다.")

    
    con.close()

# 학생 정보 목록 리스트

In [7]:
#LIST
import sqlite3
def slist():
    con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
    cur = con.cursor()

    sql = "select * from TSTUDENT;"

    cur.execute(sql)

    rows = cur.fetchall()

    for row in rows:
        print(row)

    con.close()

# 학생 정보 관리 통합

In [8]:
import sqlite3

con = sqlite3.connect("C:/Users/kowm6/Desktop/학생테이블.db")
cur = con.cursor()

def ann():
    print("\n")
    print("1: 학생 정보 입력")
    print("2: 학생 정보 수정")
    print("3: 학생 정보 삭제")
    print("4: 학생 정보 검색")
    print("5: 학생 정보 목록")
    print("0: 종료")
    print("\n")
    
    v = int(input("원하는 번호를 선택하세요 : "))

    if v == 0:
        print("프로그램 종료")
        return
    
    if v == 1:
        print("학생 정보 입력")
        insert()
        ann()
    elif v == 2:
        print("기존 학생 정보 수정 ")
        updata()
        ann()
    elif v == 3:
        print("학생 정보 삭제 ")
        delete()
        ann()
    elif v == 4:
        print("학생 정보 검색 ")
        search()
        ann()
    elif v == 5:
        print("학생 정보 목록")
        slist()
        ann()
    else:
        print("알맞은 숫자를 입력해주세요")
        ann()
        
ann()

1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 5
학생 정보 목록
('201514005', '백지혜', '여', '역사문화', '010-8781-6030', '55060', '효자동3가')
('201355052', '이호영', '남', '스마트미디어', '010-1234-5577', '55068', '농소4길')
('201462006', '김성민', '남', '스마트미디어', '010-5601-9708', '55060', '효자동3가')
('201362054', '김평화', '남', '스마트미디어', '010-3131-7937', '55080', '효자동1가')
('201462039', '이창혁', '남', '스마트미디어', '010-7273-8304', '54123', '백터로93')
('201662039', '이채연', '여', '스마트미디어', '010-5555-1111', '55083', '삼천동')
('201662021', '양수연', '여', '스마트미디어', '010-7640-1234', '55083', '삼천동')
('201662025', '오희상', '남', '스마트미디어', '010-1234-4321', '55083', '삼천동')
('201662049', '김민규', '남', '스마트미디어', '010-3153-5000', '55566', '효자동')
('201662042', '이유미', '여', '스마트미디어', '010-5432-8105', '57165', '정읍시')
('201662071', '최희은', '여', '스마트미디어', '010-9065-7150', '39175', '구미시')
('201662067', '김준하', '남', '스마트미디어', '010-0000-0000', '55023', '인후동')
('201662062', '조태현', '남', '스마트미디어', '010-3390-0000', '54084', '익산시')
('201662053', '정유림', '여', '스마트미디어', '010-3333-2222', '58456', '부안군')
('201319040', '최제현', '남', '일본언어문화', '010-6433-8855', '55039', '덕진구')
('201662054', '황수진', '여', '스마트미디어', '010-6659-1234', '56789', '102-807')
('201662055', '김유진', '여', '스마트미디어', '010-3357-1245', '51139', '103-402')
('201370065', '문예진', '여', '게임콘텐츠', '010-1100-2213', '55009', '101-102')
('201652015', '윤나연', '여', '스마트미디어', '010-3412-3456', '51234', '스타타워')
('201662069', '정소영', '여', '스마트미디어', '010-5305-9026', '54945', '105-1601')
('201662028', '이승연', '여', '스마트미디어', '010-6690-9690', '54858', '104-1801')
('201662017', '박찬영', '여', '스마트미디어', '010-6534-8828', '54965', '다드림빌')
('201519006', '이은예', '여', '일본언어문화', '010-1234-4321', '35910', '홍연성빌')
('201619039', '위은지', '여', '일본언어문화', '010-4111-3035', '55069', '스타빌')
('201662036', '조혜민', '여', '스마트미디어', '010-1111-2222', '54648', '스타홈')
('201151033', '김동녘', '남', '스마트미디어', '010-6613-5530', '56075', '스마트')
('201317039', '김양원', '남', '일본언어문화', '010-0000-0000', '51120', '전주대')
('201523060', '박수현', '여', '사회복지', '010-2959-0754', '54348', '김제시')
('201625024', '나다정', '여', '문헌정보', '010-3654-5654', '54624', '익산시')
('201362022', '권성수', '남', '스마트미디어', '010-6733-7942', '54666', '하모니빌')
('201362009', '박정현', '남', '스마트미디어', '010-1112-2223', '55555', '202호')
('201662041', '김재연', '남', '스마트미디어', '010-2779-6046', '54902', '504호')
('201662040', '우은성', '여', '스마트미디어', '010-2222-3335', '59409', '스타타워')
('201662024', '김유진', '여', '스마트미디어', '010-1234-5678', '54123', '전주시')
('201462074', '정진영', '남', '스마트미디어', '010-3326-2579', '51101', '전주시')


1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 4
학생 정보 검색
검색할 학생 학번 입력: 202192006
해당하는 학생의 정보가 없습니다.


1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 201362022
알맞은 숫자를 입력해주세요


1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 4
학생 정보 검색
검색할 학생 학번 입력: 201462074
학번:  201462074
이름:  정진영
성별:  남
전공:  스마트미디어
전화번호:  010-3326-2579
우편번호:  51101
주소:  전주시


1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 1
학생 정보 입력
학번 : 202192006
이름 : 최장호
성별 : 남
전공 : 인공지능학과
전화번호 : 010-2848-6170
우편번호 : 5555
주소 : 전주


1: 학생 정보 입력
2: 학생 정보 수정
3: 학생 정보 삭제
4: 학생 정보 검색
5: 학생 정보 목록
0: 종료


원하는 번호를 선택하세요 : 0
프로그램 종료